### ISSUE TITLE
[TODO] autoban.py module

### ISSUE THREAD

**Issue by Technetium1** [JohnRipper/QuantumJump#10]
Add a bad nick and bad account list for automatic bans.
- [ ] `ba` to add bad accounts
- [ ] `bn` to add bad nicknames
- [ ] Default to 6 month ban (longest possible)
- [ ] Only accept commands from users that have the ban permission!
- [ ] Option that triggers kicks instead of bans
- [ ] Log autobans and give them a pretty color in console
- [ ] Option to say in chat why the account was banned
- [ ] Ignore character cases, `_`, `-`, `[`, `]`, and `|`
- [ ] Option to ban partial matches, and decide how specific the matches should be
- [ ] Ignore anyone that joins with a role
- [ ] Figure out where to put the banlist files
- [ ] Possibly name `roomname_badaccounts.txt` and `roomname_badnicks.txt`
- [ ] Add a command to forgive the most recent ban

**Comment by NordCox** [comment]
Sweet, I love this bot, and hopes you continue work on it

**Comment by Technetium1** [comment]
This is indefinitely on hold since [Jumpinchat is shutting down.](https://blog.jumpin.chat/jumpinchat-update-shutting-down-march-2nd-2021/)
